
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);
INSERT INTO users (name, age) VALUES("Ruth", 20);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES("The Board Game", "The Board Game", 1000, '10-10-2018', '10-11-2018');

INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(1000,1,1);
